### ISSUE TITLE
多段中継時に X-Forwarded-Proto などが引き継がれない

### ISSUE THREAD

**Issue by lobin-z0x50** [neogenia-jp/EzGate#19]
EzGate を多段で中継させたとき、`X-Forwarded-Proto` などが引き継がれない。

例えば以下のように ２段にしたとき、Webアプリから見ると `X-Forwarded-Proto: http` となってしまう。正しくは `https` であるべき。 
`X-Real-IP` も EzGate1 の IP になっていると思われる。

```
ブラウザ
↓ https
EzGate1
↓ http
EzGate2 (no_ssl mode)
↓ http
Webアプリ
```

### 原因
EzGate2 の中継時に、 `X-Forwarded-Proto: $schema` をセットしているため。
https://github.com/neogenia-jp/EzGate/blob/4298ac788282eec601cd6b585ab9f4f325c3aad8/docker/resources/scripts/config_template_http.erb#L46

**Comment by haruyan-hopemucci** [comment]
WebSocket(ws, wss)でも同様の問題が起こっていそうです。

<img width="1107" alt="image" src="https://github.com/neogenia-jp/EzGate/assets/68041476/b4d2c424-97f8-41de-adea-1aa2d7c496cc">

**Comment by haruyan-hopemucci** [comment]
https://github.com/neogenia-jp/L-Order/issues/1017#issuecomment-1943136318

`X-Forwarded-Proto`に関しては上記の方法で解決できそうです。

**Comment by lobin-z0x50** [comment]
> X-Forwarded-Protoに関しては上記の方法で解決できそうです。

コメントありがとうございます。
そのプロジェクトでは、回避方法が見つかった、ということですね。よかったです。

https://qiita.com/shisashi/items/25892561ab0e7deeaba5
によると、以下のようにすればいけるかも。
```
    map $http_x_forwarded_for $xff {
        default $http_x_forwarded_for;
        "" $scheme;
    }
    proxy_set_header X-Forwarded-Proto $xff; 
```
